#include "errortable.h"

struct  error_table windows_errno []={
{ "EPERM", 1, "Operation not permitted" },
{ "ENOENT", 2, "No such file or directory" },
{ "ESRCH", 3, "No such process" },
{ "EINTR", 4, "Interrupted function call" },
{ "EIO", 5, "Input/output error" },
{ "ENXIO", 6, "No such device or address" },
{ "E2BIG", 7, "Arg list too long" },
{ "ENOEXEC", 8, "Exec format error" },
{ "EBADF", 9, "Bad file descriptor" },
{ "ECHILD", 10, "No child processes" },
{ "EAGAIN", 11, "Resource temporarily unavailable" },
{ "ENOMEM", 12, "Not enough space" },
{ "EACCES", 13, "Permission denied" },
{ "EFAULT", 14, "Bad address" },
{ "EBUSY", 16, "Resource device" },
{ "EEXIST", 17, "File exists" },
{ "EXDEV", 18, "Improper link" },
{ "ENODEV", 19, "No such device" },
{ "ENOTDIR", 20, "Not a directory" },
{ "EISDIR", 21, "Is a directory" },
{ "ENFILE", 23, "Too many open files in system" },
{ "EMFILE", 24, "Too many open files" },
{ "ENOTTY", 25, "Inappropriate I/O control operation" },
{ "EFBIG", 27, "File too large" },
{ "ENOSPC", 28, "No space left on device" },
{ "ESPIPE", 29, "Invalid seek" },
{ "EROFS", 30, "Read-only file system" },
{ "EMLINK", 31, "Too many links" },
{ "EPIPE", 32, "Broken pipe" },
{ "EDOM", 33, "Domain error" },
{ "EDEADLK", 36, "Resource deadlock avoided" },
{ "ENAMETOOLONG", 38, "Filename too long" },
{ "ENOLCK", 39, "No locks available" },
{ "ENOSYS", 40, "Function not implemented" },
{ "ENOTEMPTY", 41, "Directory not empty" },
{ "EINVAL", 22, "Invalid argument" },
{ "ERANGE", 34, "Result too large" },
{ "EILSEQ", 42, "Illegal byte sequence" },
{ "STRUNCATE", 80, "Unknown error" },
{ "EADDRINUSE", 100, "Unknown error" },
{ "EADDRNOTAVAIL", 101, "Unknown error" },
{ "EAFNOSUPPORT", 102, "Unknown error" },
{ "EALREADY", 103, "Unknown error" },
{ "EBADMSG", 104, "Unknown error" },
{ "ECANCELED", 105, "Unknown error" },
{ "ECONNABORTED", 106, "Unknown error" },
{ "ECONNREFUSED", 107, "Unknown error" },
{ "ECONNRESET", 108, "Unknown error" },
{ "EDESTADDRREQ", 109, "Unknown error" },
{ "EHOSTUNREACH", 110, "Unknown error" },
{ "EIDRM", 111, "Unknown error" },
{ "EINPROGRESS", 112, "Unknown error" },
{ "EISCONN", 113, "Unknown error" },
{ "ELOOP", 114, "Unknown error" },
{ "EMSGSIZE", 115, "Unknown error" },
{ "ENETDOWN", 116, "Unknown error" },
{ "ENETRESET", 117, "Unknown error" },
{ "ENETUNREACH", 118, "Unknown error" },
{ "ENOBUFS", 119, "Unknown error" },
{ "ENODATA", 120, "Unknown error" },
{ "ENOLINK", 121, "Unknown error" },
{ "ENOMSG", 122, "Unknown error" },
{ "ENOPROTOOPT", 123, "Unknown error" },
{ "ENOSR", 124, "Unknown error" },
{ "ENOSTR", 125, "Unknown error" },
{ "ENOTCONN", 126, "Unknown error" },
{ "ENOTRECOVERABLE", 127, "Unknown error" },
{ "ENOTSOCK", 128, "Unknown error" },
{ "ENOTSUP", 129, "Unknown error" },
{ "EOPNOTSUPP", 130, "Unknown error" },
{ "EOTHER", 131, "Unknown error" },
{ "EOVERFLOW", 132, "Unknown error" },
{ "EOWNERDEAD", 133, "Unknown error" },
{ "EPROTO", 134, "Unknown error" },
{ "EPROTONOSUPPORT", 135, "Unknown error" },
{ "EPROTOTYPE", 136, "Unknown error" },
{ "ETIME", 137, "Unknown error" },
{ "ETIMEDOUT", 138, "Unknown error" },
{ "ETXTBSY", 139, "Unknown error" },
{ "EWOULDBLOCK", 140, "Unknown error" }
};

